import type { SiteConfig } from './types'

export const DEFAULT_SITE_CONFIG: SiteConfig = {
  name: '友军博品',
  showName: true,
  logo: '/website-logo.svg',
  footerLogo: '/website-logo.svg',
  favicon: '',
  navigation: [
    { label: '首页', href: '/' },
    { label: '企业', href: '/companies' },
    { label: '需求', href: '/demands' },
    { label: '行业资讯', href: '/news' },
  ],
  quickLinks: [
    { label: '首页', href: '/' },
    { label: '企业', href: '/companies' },
    { label: '需求', href: '/demands' },
    { label: '行业资讯', href: '/news' },
  ],
  showContactButton: true,
  contactButtonText: '联系客服',
  footerDescription: '汇聚产业链优质企业资源，快速寻找合作伙伴、供应商、技术服务与人才资源，让产业对接更高效。',
  phone: '18915532743',
  email: '18915532743@163.com',
  address: '苏州园区汀兰巷192号 沙湖天地 A1-205B-11',
  contactQr: '/wecom-qrcode.jpg',
  contactBanner: '/contact-banner.png',
  contactEyebrow: '联系我们',
  contactTitle: '统一进入平台客服',
  contactDescription: '合作咨询、资源入驻、项目需求和供应商对接全部提交为留言，由平台客服人工跟进。',
  contactFormTitle: '提交留言',
  contactFormDescription: '留言会进入后台留言管理，客服将根据内容进行跟进。',
  homeFeaturesTitle: '让产业资源更容易被找到',
  homeFeatures: [
    { icon: 'factory', title: '产业资源整合', description: '汇聚产业链上下游资源' },
    { icon: 'package', title: '快速查找', description: '按分类快速查询企业' },
    { icon: 'globe', title: '需求共享', description: '及时了解企业合作需求' },
    { icon: 'users', title: '高效对接', description: '帮助企业建立合作机会' },
  ],
  copy: {
    home: {
      demandsTitle: '最新需求动态',
      demandsDescription: '聚焦企业最新业务动态，展示合作需求、项目信息及行业资讯，促进产业资源高效对接。',
      demandsLinkText: '查看更多需求',
      newsTitle: '行业资讯',
      newsLinkText: '查看全部资讯',
    },
    companies: {
      title: '全部企业',
      description: '按企业分类查看资源，所有合作咨询统一进入平台客服。',
      allLabel: '全部',
    },
    demands: {
      title: '最新需求动态',
      description: '聚焦企业最新业务动态，展示合作需求、项目信息及行业资讯，促进产业资源高效对接。',
    },
    news: {
      title: '产业观察与资讯',
      description: '持续整理自动化、供应链、技术服务和项目对接相关动态。',
    },
    search: {
      eyebrow: '搜索',
      title: '搜索结果',
      description: '可搜索企业名称、主营业务、需求标题、地区和关键词。',
      companiesTitle: '企业结果',
      demandsTitle: '需求结果',
      companiesEmpty: '暂无匹配企业。',
      demandsEmpty: '暂无匹配需求。',
    },
    companyDetail: {
      matchTitle: '平台对接',
      matchDescription: '企业电话、微信、联系人不直接展示。请提交留言，由平台客服确认需求后人工撮合。',
    },
  },
  theme: {
    primary: '#1E40AF',
    primaryDark: '#111827',
    accent: '#FF6B6B',
    pageBackground: '#FFFFFF',
    cardBackground: '#FFFFFF',
    bodyText: '#6B7280',
    border: '#E5E7EB',
    mutedBackground: '#F9FAFB',
    headerBackground: '#F3F4F6',
    headerOpacity: 100,
    headerText: '#111827',
    headerHoverText: '#1E40AF',
    footerBackground: '#F3F4F6',
    footerText: '#111827',
    footerLink: '#1E40AF',
    fontFamily: 'Inter',
  },
  seo: {
    title: '友军博品',
    description: '友军博品企业资源与项目需求对接平台。',
    keywords: '工厂自动化,产业资源,企业需求,供应商,工程师服务',
  },
}
