import type { SiteConfig } from './types'

export const DEFAULT_SITE_CONFIG: SiteConfig = {
  name: '友军博品',
  showName: true,
  logo: '/website-logo.svg',
  footerLogo: '/website-logo.svg',
  favicon: '',
  navigation: [
    { label: '首页', href: '/' },
    { label: '企业', href: '/companies' },
    { label: '需求', href: '/demands' },
    { label: '行业资讯', href: '/news' },
  ],
  quickLinks: [
    { label: '首页', href: '/' },
    { label: '企业', href: '/companies' },
    { label: '需求', href: '/demands' },
    { label: '行业资讯', href: '/news' },
  ],
  showContactButton: true,
  contactButtonText: '联系客服',
  footerDescription: '汇聚产业链优质企业资源，快速寻找合作伙伴、供应商、技术服务与人才资源，让产业对接更高效。',
  phone: '18915532743',
  email: '18915532743@163.com',
  address: '苏州园区汀兰巷192号 沙湖天地 A1-205B-11',
  contactQr: '/wecom-qrcode.jpg',
  contactBanner: '/contact-banner.png',
  contactEyebrow: '联系我们',
  contactTitle: '统一进入平台客服',
  contactDescription: '合作咨询、资源入驻、项目需求和供应商对接全部提交为留言，由平台客服人工跟进。',
  contactFormTitle: '提交留言',
  contactFormDescription: '留言会进入后台留言管理，客服将根据内容进行跟进。',
  homeFeaturesTitle: '让产业资源更容易被找到',
  homeFeatures: [
    { icon: 'factory', title: '产业资源整合', description: '汇聚产业链上下游资源' },
    { icon: 'package', title: '快速查找', description: '按分类快速查询企业' },
    { icon: 'globe', title: '需求共享', description: '及时了解企业合作需求' },
    { icon: 'users', title: '高效对接', description: '帮助企业建立合作机会' },
  ],
  theme: {
    primary: '#1E40AF',
    primaryDark: '#111827',
    accent: '#FF6B6B',
    pageBackground: '#FFFFFF',
    cardBackground: '#FFFFFF',
    bodyText: '#6B7280',
    border: '#E5E7EB',
    mutedBackground: '#F9FAFB',
    headerBackground: '#F3F4F6',
    headerOpacity: 100,
    headerText: '#111827',
    headerHoverText: '#1E40AF',
    footerBackground: '#F3F4F6',
    footerText: '#111827',
    footerLink: '#1E40AF',
    fontFamily: 'Inter',
  },
  seo: {
    title: '友军博品',
    description: '友军博品企业资源与项目需求对接平台。',
    keywords: '工厂自动化,产业资源,企业需求,供应商,工程师服务',
  },
}
